server:
  port: 8080
spring:
  datasource:
    druid:
     url: jdbc:mysql://127.0.0.1:3306/springboot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     initial-size: 10
     max-active: 100
     min-idle: 10
     max-wait: 60000
     pool-prepared-statements: true
     max-pool-prepared-statement-per-connection-size: 20
     time-between-eviction-runs-millis: 60000
     min-evictable-idle-time-millis: 300000
     test-while-idle: true
     test-on-borrow: false
     test-on-return: false
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-wait: -1ms
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000



